name: knowme_frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # HTTP Client
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Logging
  logger: ^2.0.2+1

  # UI
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.12
  google_fonts: ^6.1.0
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/bottom_nav_svgs/
    - assets/logos/
    - assets/posts_images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
