name: Setup Flutter

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.29.3'
            channel: "stable"
            cache-key: flutter-linux-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
            cache-path: ~/.pub-cache

      - name: Add Flutter to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Debug PATH and Flutter
        run: |
          echo $PATH
          ls -l ~/.pub-cache  

      - name: Verify Flutter installation
        run: flutter doctor -v


      - name: Clean and upgrade dependencies
        run: |
          flutter pub upgrade
          flutter pub cache repair
          flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: |
          if [ -d "test" ]; then
            flutter test;
          else
            echo "No tests directory found, skipping tests.";
          fi

  build_android:
    name: Build Android APK
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"
          cache-key: flutter-linux-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          cache-path: ~/.pub-cache

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release