name: Flutter CI

on:
  pull_request:
    branches: [main, develop, "feature/*"]   # 필요한 PR 대상 브랜치 다 추가
  push:
    branches: [main, develop, "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release