name: Setup Flutter

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # (Optional) 환경 점검 - Flutter 및 PATH
      - name: Debug Environment
        run: |
          echo "Debugging environment..."
          echo "PATH: $PATH"
          which flutter || echo "Flutter binary not found in PATH"
          flutter --version
          ls -la $HOME/.pub-cache

      # 의존성 설치/업그레이드
      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade --force

      # 포맷 검사
      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      # 코드 분석
      - name: Analyze project source
        run: flutter analyze

      # 테스트 실행
      - name: Run tests
        run: |
          if [ -d "test" ]; then
            flutter test;
          else
            echo "No tests directory found, skipping tests.";
          fi

      # 디버깅 (실패시만)
      - name: Debug (If needed)
        if: ${{ failure() }}
        run: |
          echo "DEBUG INFO"
          which flutter || echo "Flutter binary not found in PATH"
          echo $PATH
          flutter doctor -v
          ls -la ~/.pub-cache
          ls -la ~/.pub-cache/bin
          ls -la ~/.pub-cache/flutter/bin

  build_android:
    name: Build Android APK
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release